<!doctypehtml><html lang="ko"><meta charset="utf-8"><title>에러 경계(Error Boundaries)</title><meta name="viewport"content="width=device-width,initial-scale=1"><link rel="stylesheet"href="https://raw.githubusercontent.com/shinokada/prism-coy-theme/main/theme_common.css"><section id="에러-경계error-boundaries"class="level1"><h1>에러 경계(Error Boundaries)</h1><p>과거에는 컴포넌트 내부의 자바스크립트 에러가 React의 내부 상태를 훼손하고 다음 렌더링에서 <a href="https://github.com/facebook/react/issues/6895">암호화</a> <a href="https://github.com/facebook/react/issues/8579">에러</a> <a href="https://github.com/facebook/react/issues/4026">방출</a>을 유발하곤 했습니다. 이러한 에러는 항상 애플리케이션 코드의 이전 단계의 에러로 인해 발생했지만, React는 컴포넌트 내에서 에러를 정상적으로 처리할 수 있는 방법을 제공하지 않아 이를 복구할 수가 없었습니다.<section id="introducing-error-boundaries"class="level2"><h2>에러 경계의 소개</h2><p>UI의 일부분에 존재하는 자바스크립트 에러가 전체 애플리케이션을 중단시켜서는 안 됩니다. React 사용자들이 겪는 이 문제를 해결하기 위해 React 16에서는 에러 경계(“error boundary”)라는 새로운 개념이 도입되었습니다.<p>에러 경계는 <strong>하위 컴포넌트 트리의 어디에서든 자바스크립트 에러를 기록하며 깨진 컴포넌트 트리 대신 폴백 UI를 보여주는</strong> React 컴포넌트입니다. 에러 경계는 렌더링 도중 생명주기 메서드 및 그 아래에 있는 전체 트리에서 에러를 잡아냅니다.<blockquote><p>Note<p>에러 경계는 다음과 같은 에러는 포착하지 <strong>않습니다</strong>.<ul><li>이벤트 핸들러 (<a href="#how-about-event-handlers">더 알아보기</a>)<li>비동기적 코드 (예: <code>setTimeout</code> 혹은 <code>requestAnimationFrame</code> 콜백)<li>서버 사이드 렌더링<li>자식에서가 아닌 에러 경계 자체에서 발생하는 에러</ul></blockquote><p>생명주기 메서드인 <a href="./react-component.html#static-getderivedstatefromerror"><code>static getDerivedStateFromError()</code></a> 와 <a href="./react-component.html#componentdidcatch"><code>componentDidCatch()</code></a> 중 하나 (혹은 둘 다)를 정의하면 클래스 컴포넌트 자체가 에러 경계가 됩니다. 에러가 발생한 뒤에 폴백 UI를 렌더링하려면 <code>static getDerivedStateFromError()</code>를 사용하세요. 에러 정보를 기록하려면 <code>componentDidCatch()</code>를 사용하세요.<pre class="language-js{7-10,12-15,18-21}"><code class="language-js{7-10,12-15,18-21}">class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // 다음 렌더링에서 폴백 UI가 보이도록 상태를 업데이트 합니다.
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    // 에러 리포팅 서비스에 에러를 기록할 수도 있습니다.
    logErrorToMyService(error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      // 폴백 UI를 커스텀하여 렌더링할 수 있습니다.
      return &#x3C;h1>Something went wrong.&#x3C;/h1>;
    }

    return this.props.children;
  }
}</code></pre><p>그런 다음엔 아래와 같이 일반 컴포넌트로 사용할 수 있습니다.<pre class="language-js"><code class="language-js"><span class="token operator">&#x3C;</span><span class="token maybe-class-name">ErrorBoundary</span><span class="token operator">></span>
  <span class="token operator">&#x3C;</span><span class="token maybe-class-name">MyWidget</span> <span class="token operator">/</span><span class="token operator">></span>
<span class="token operator">&#x3C;</span><span class="token operator">/</span><span class="token maybe-class-name">ErrorBoundary</span><span class="token operator">></span></code></pre><p>에러 경계는 자바스크립트의 <code>catch {}</code> 구문과 유사하게 동작하지만 컴포넌트에 적용됩니다. 오직 클래스 컴포넌트만이 에러 경계가 될 수 있습니다. 실제로도 대부분의 경우 에러 경계 컴포넌트를 한 번만 선언하여 애플리케이션 전체에서 활용하려고 할 것입니다.<p><strong>에러 경계는 트리 내에서 하위에 존재하는 컴포넌트의 에러만을 포착합니다</strong>. 에러 경계 자체적으로는 에러를 포착할 수 없습니다. 에러 경계가 에러 메시지를 렌더링하는 데에 실패한다면 에러는 그 위의 가장 가까운 에러 경계로 전파될 것입니다. 이 또한 자바스크립트의 <code>catch {}</code> 구문이 동작하는 방식과 유사합니다.</section><section id="live-demo"class="level2"><h2>라이브 데모</h2><p><a href="https://codepen.io/gaearon/pen/wqvxGa?editors=0010">에러 경계 선언과 사용 예시</a>를 참고하세요.</section><section id="where-to-place-error-boundaries"class="level2"><h2>에러 경계를 배치할 위치</h2><p>에러 경계의 좀 더 세분화된 부분은 개발자에게 달려있습니다. 서버 사이드 프레임워크가 충돌을 해결하는 것처럼 최상위 경로의 컴포넌트를 감싸서 유저에게 “문제가 발생했습니다”라는 메시지를 보여줄 수 있습니다. 또한 에러 경계의 각 위젯을 에러 경계로 감싸서 애플리케이션의 나머지 부분이 충돌하지 않도록 보호할 수도 있습니다.</section><section id="new-behavior-for-uncaught-errors"class="level2"><h2>포착되지 않는 에러에 대한 새로운 동작</h2><p>이 변경사항은 중요한 의미를 갖습니다. <strong>React 16부터는 에러 경계에서 포착되지 않은 에러로 인해 전체 React 컴포넌트 트리의 마운트가 해제됩니다.</strong><p>우리는 이 결정에 대해서 논의했지만 우리의 경험에 따르면 손상된 UI를 완전히 제거하는 것보다 그대로 남겨두는 것이 더 좋지 않습니다. 예를 들어 메신저와 같은 제품에서 손상된 UI를 그대로 남겨두면 누군가가 잘못된 사람에게 메시지를 보내게 될 가능성이 있습니다. 마찬가지로 결제 앱의 예를 들면 잘못된 금액을 보여주는 것이 아무 것도 렌더링하지 않는 것보다 더 나쁩니다.<p>이 변경사항은 React 16으로 마이그레이션 할 때 애플리케이션에서 이전에 알려지지 않았던 기존에 존재하던 충돌을 발견할 수 있음을 의미합니다. 에러 경계를 추가함으로써 문제가 발생했을 때 더 나은 사용자 경험을 제공할 수 있습니다.<p>예를 들어 페이스북 메신저는 사이드 바, 정보 패널, 대화 기록과 메시지 입력을 각각 별도의 에러 경계로 감싸두었습니다. 이 UI 영역 중 하나의 컴포넌트에서 충돌이 발생하면 나머지 컴포넌트는 대화형으로 유지됩니다.<p>또한 프로덕션 환경에서 발생한 처리되지 않은 예외 상황에 대하여 학습하고 수정할 수 있도록 자바스크립트 에러 리포팅 서비스를 활용하거나 직접 작성하는 것을 권장합니다.</section><section id="component-stack-traces"class="level2"><h2>컴포넌트 스택 추적</h2><p>React 16은 애플리케이션이 실수로 에러를 집어삼킨 경우에도 개발 과정에서 렌더링하는 동안 발생한 모든 에러를 콘솔에 출력합니다. 에러 메시지 및 자바스크립트 스택과 더불어 React 16은 컴포넌트 스택 추적 또한 제공합니다. 이제 정확히 컴포넌트 트리의 어느 부분에서 에러가 발생했는지 확인할 수 있게 되었습니다.</p><img src="./docs/error-boundaries-stack-trace.png"style="max-width:100%"alt="에러 경계에 의해 포착된 에러"><p>또한 컴포넌트 스택 추적 내에서 파일 이름과 줄 번호도 확인할 수 있습니다. 이는 <a href="https://github.com/facebookincubator/create-react-app">Create React App</a> 프로젝트 내에서 기본적으로 동작합니다.</p><img src="./docs/error-boundaries-stack-trace-line-numbers.png"style="max-width:100%"alt="에러 경계에 의해 줄 번호와 함께 포착된 에러"><p>Create React App을 사용하지 않는 경우에는 수동으로 <a href="https://www.npmjs.com/package/@babel/plugin-transform-react-jsx-source">이 플러그인</a>을 Babel 설정을 추가할 수 있습니다. 이 기능은 개발 단계를 위해서만 제작되었으며 <strong>프로덕션 환경에서는 비활성화 해야합니다</strong>.<blockquote><p>주의<p>스택 추적에 표시되는 컴포넌트 이름은 <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name"><code>Function.name</code></a> 프로퍼티에 따라 다릅니다. 아직 기본적으로 제공하지 않는 구형 브라우저 혹은 디바이스(예: IE11)를 지원하는 경우 번들 애플리케이션에 <a href="https://github.com/JamesMGreene/Function.name"><code>function.name-polyfill</code></a>과 같은 <code>Function.name</code> 폴리필(Polyfill)을 포함시키는 것을 고려해볼 수 있습니다. 또는 모든 컴포넌트에서<a href="./react-component.html#displayname"><code>displayName</code></a> 프로퍼티를 명시적으로 설정할 수도 있습니다.</blockquote></section><section id="how-about-trycatch"class="level2"><h2>try/catch는 어떤가요?</h2><p><code>try</code> / <code>catch</code>는 훌륭하지만 명령형 코드에서만 동작합니다.<pre class="language-js"><code class="language-js"><span class="token keyword control-flow">try</span> <span class="token punctuation">{</span>
  <span class="token function">showButton</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> <span class="token keyword control-flow">catch</span> <span class="token punctuation">(</span>error<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token comment">// ...</span>
<span class="token punctuation">}</span></code></pre><p>그러나 React 컴포넌트는 선언적이며 <em>무엇</em>을 렌더링할지 구체화합니다.<pre class="language-js"><code class="language-js"><span class="token operator">&#x3C;</span><span class="token maybe-class-name">Button</span> <span class="token operator">/</span><span class="token operator">></span></code></pre><p>에러 경계는 React의 선언적인 특성을 보존하고 예상한 대로 동작합니다. 예를 들어 트리의 깊숙한 어딘가에 있는<code>setState</code>에 의해 유발된 <code>componentDidUpdate</code> 메서드에서 에러가 발생하더라도 가장 가까운 에러 경계에 올바르게 전달됩니다.</section><section id="how-about-event-handlers"class="level2"><h2>이벤트 핸들러는 어떤가요?</h2><p>에러 경계는 이벤트 핸들러 내부에서는 에러를 포착하지 <strong>않습니다</strong>.<p>React는 이벤트 핸들러의 에러를 해결하기 위해서 에러 경계를 필요로 하지 않습니다. render 메서드 및 생명주기 메서드와 달리 이벤트 핸들러는 렌더링 중에 발생하지 않습니다. 따라서 이벤트 핸들러가 에러를 던져도 React는 여전히 화면에 무엇을 표시해야 할 지 알고 있습니다.<p>이벤트 핸들러 내에서 에러를 잡아야 하는 경우에 일반 자바스크립트의 <code>try</code> / <code>catch</code> 구문을 사용하세요.<pre class="language-js{9-13,17-20}"><code class="language-js{9-13,17-20}">class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = { error: null };
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    try {
      // 에러를 던질 수 있는 무언가를 해야합니다.
    } catch (error) {
      this.setState({ error });
    }
  }

  render() {
    if (this.state.error) {
      return &#x3C;h1>Caught an error.&#x3C;/h1>
    }
    return &#x3C;button onClick={this.handleClick}>Click Me&#x3C;/button>
  }
}</code></pre><p>위의 예시는 일반적인 자바스크립트의 동작을 보여주며 에러 경계를 사용하지 않습니다.</section><section id="naming-changes-from-react-15"class="level2"><h2>React 15에서 변경된 명명법</h2><p>React 15는 <code>unstable_handleError</code>라는 다른 메서드 이름으로 에러 경계에 대해 매우 제한적인 지원을 포함하고 있었습니다. 이 메서드는 더 이상 동작하지 않으며 첫 16 베타 릴리즈부터 코드에서 <code>componentDidCatch</code>로 변경해야 합니다.<p>이 변경사항을 위해 코드를 자동으로 마이그레이션하기 위한 <a href="https://github.com/reactjs/react-codemod#error-boundaries">codemod</a>를 제공했습니다. <span style="float:footnote"><a href="./index.html#toc">Go to TOC</a></span></section></section>